### ISSUE TITLE
Compaction code missing a step?

### ISSUE THREAD

**Issue by MobiZaman** [uknfire/orthogonal-drawing#2]
Hi,
I am not sure if this is an issue or a missing feature, but according to your readme file, this code is based on the approach mentioned in "A Generic Framework for the Topology-Shape-Metrics Based Layout". Now, this paper mentions in the first paragraph of section 5.1 that 

> Tamassia defined some restrictions to make such a computation possible. The compaction by Tamassia requires orthogonal representations that contain no bends as input. Furthermore, each face of the input has to have a rectangular shape.

But I cannot find the section in your code which implements the part about making faces rectangular. Isnt this supposed to be a part of the compaction step? The output of the orthogonalization doesn't seem to be working well because of this. Or is this part already implemented somewhere in the code?

**Comment by MobiZaman** [comment]
I believe that this is what is causing the node and edge overlaps.

**Comment by rawfh** [comment]
Sorry, I didn't notice this issue until today.

You're right. The reason is that I got into trouble implementing `refine_faces()`. The code is still buggy, and I guess it is the most complicated part of this algorithm.

**Comment by MobiZaman** [comment]
I have implemented this part of the algorithm. But i am still testing it out.

**Comment by uknfire** [comment]
Finally, I fully implemented `refine_faces()` and passed all tests. (It's a really heavy and complicated task, congraduation!)
